# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "mambaforge-latest"
  jobs:
    install:
      - pip list
      - pip install -r devtools/conda-envs/requirements.txt
      - pip list
      - pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ .
      - pip list

sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .

conda:
  environment: devtools/conda-envs/docs_env.yaml
