# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: mambaforge-4.10 # Python version is specified in Conda environment
  jobs:
    post_build:
      - PIP_NO_DEPS=1

sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .

conda:
  environment: devtools/conda-envs/docs_env.yaml

formats:
  - pdf
