# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: mambaforge-4.10 # Python version is specified in Conda environment
  jobs:
    pre_build:
      - mamba list
      - pip list
    install:
      - pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ .

sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .

conda:
  environment: devtools/conda-envs/docs_env.yaml

formats:
  - pdf
