name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    name: 💻=${{ matrix.os }}, env=${{ matrix.environment }},
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        environment:
          - py311pint24
          - py312pint24
          - py313pint24
          - py314pint24
          - py311pint24openmm
          - py312pint24openmm
          - py313pint24openmm
          - py314pint24openmm
          - py311pint25
          - py312pint25
          - py313pint25
          - py314pint25
          - py311pint25openmm
          - py312pint25openmm
          - py313pint25openmm
          - py314pint25openmm

    steps:
    - uses: actions/checkout@v6

    - uses: prefix-dev/setup-pixi@v0.9.5
      with:
        pixi-version: v0.66.0
        environments: ${{ matrix.environment }}

    - name: Run type-checker
      run: pixi run -e ${{ matrix.environment }} run_mypy

    - name: Run unit tests
      run: pixi run -e ${{ matrix.environment }} run_tests

    - name: Run dummy package tests
      run: pixi run -e ${{ matrix.environment }} run_dummy_tests

    - name: Run docexamples
      if: ${{ contains(matrix.environment, 'openmm') }}
      run: pixi run -e ${{ matrix.environment }} run_docexamples

    - name: Check OpenMM is lazy-imported
      if: ${{ !contains(matrix.environment, 'openmm') }}
      run: pixi run -e ${{ matrix.environment }} python -c "import sys; from openff.units import unit, Quantity; assert 'openmm' not in sys.modules"

    - name: Codecov
      uses: codecov/codecov-action@v6
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        fail_ci_if_error: false
